FROM node:18-alpine
label maintainer="RonnySali"
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
Expose 3000
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
ENV PROXY_API=$PROXY_API

CMD ["npm","start"]