version: '1'
services:
  yolo-database:
   image: mongo:jammy
   environment:
     MONGO_DB:yolomy
   ports:
     -27017:27017
    networks:
      -yolo-netservices
    volumes:
      -yolo-data:/etc/backend
 yolo-client:
   image: salisimiyu/ronny_client:v1
   environment:
     PORT:3000
     PROXY_API:
    ports:
      -"3000:3000"
    networks:
      -yolo-services
 yolo-backend: 
    image: ronnysimiyu/yolo-backend_img:v1
    environment:
      MONGODB_URL:
    ports:
     -"5000:5000"
    networks:
     -yolo-services
networks:
 yolo-service:
    driver:bridge
volumes:
 yolo-data
