version: '1'
services:
  yolo-database:
    image: mongo:jammy
    environment:
      MONGO_DB: yolomy
    ports:
      - 27017:27017
    networks:
      - yolo-services
    volumes:
      - yolo-data:/etc/backend
  yolo-client:
    image: salisimiyu/ronny_client:v1
    environment:
      PORT: 3000
      PROXY_API: http://yolo-backend:5000/
    ports:
      - 3000:3000
    networks:
      - yolo-services
  yolo-backend: 
    image: salisimiyu/ronny_backend:v1
    environment:
      MONGODB_URI: mongodb://yolo-database:27017/yolomy
    ports:
      - 5000:5000
    networks:
      - yolo-services
networks:
 yolo-services:
    driver: bridge
volumes:
 yolo-data:
